# Generated by Django 3.2 on 2025-01-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_info', models.CharField(max_length=277, verbose_name='新闻信息')),
            ],
        ),
    ]
