# Generated by Django 3.2 on 2025-01-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20250110_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='create_time',
            field=models.TimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
