# Generated by Django 3.2 on 2025-01-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20250113_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='', max_length=128, verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='user',
            name='nicName',
            field=models.CharField(default='', max_length=128, verbose_name='用户名'),
        ),
    ]
