# Generated by Django 3.2 on 2025-01-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_news_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
