# Generated by Django 3.2 on 2025-01-18 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20250117_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nicName',
            new_name='nickName',
        ),
    ]
