# Generated by Django 3.2 on 2025-01-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_nicname_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='', max_length=256, verbose_name='头像'),
        ),
    ]
