# Generated by Django 3.2 on 2025-01-22 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='户主姓名')),
                ('point', models.CharField(max_length=32, verbose_name='小区信息')),
                ('building', models.CharField(max_length=32, verbose_name='小区楼栋信息')),
                ('room', models.CharField(max_length=32, verbose_name='小区房间信息')),
                ('mobile', models.CharField(max_length=11, verbose_name='电话号码')),
                ('gender', models.IntegerField(choices=[(0, '女'), (1, '男')], verbose_name='性别')),
                ('idcardFront', models.CharField(max_length=64, verbose_name='身份证正面')),
                ('idcardBack', models.CharField(max_length=64, verbose_name='身份证反面')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user', verbose_name='用户')),
            ],
        ),
    ]
