# Generated by Django 3.2 on 2025-02-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20250124_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseinformation',
            name='idcardBack',
            field=models.CharField(max_length=128, verbose_name='身份证反面'),
        ),
        migrations.AlterField(
            model_name='houseinformation',
            name='idcardFront',
            field=models.CharField(max_length=128, verbose_name='身份证正面'),
        ),
    ]
