# Generated by Django 3.2 on 2025-02-11 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_repair_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepairProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='报修项目')),
            ],
        ),
        migrations.AlterField(
            model_name='repair',
            name='repairName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.repairproject', verbose_name='报修项目'),
        ),
    ]
