# Generated by Django 3.2 on 2025-02-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_repair'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepairImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=128, verbose_name='上传报修图片')),
            ],
        ),
        migrations.AddField(
            model_name='repair',
            name='attachment',
            field=models.ManyToManyField(to='api.RepairImg', verbose_name='报修图片'),
        ),
    ]
