# Generated by Django 3.2 on 2025-02-14 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20250213_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repair',
            name='attachment',
        ),
        migrations.AddField(
            model_name='repairimg',
            name='repairId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.repair', verbose_name='报修单'),
            preserve_default=False,
        ),
    ]
